version: '3.7'

services:
  node:
    container_name: node_server
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    volumes:
      - .:/app
    networks:
      - common
    environment:
      PORT: 5000
      MONGO_URI: 'mongodb://mongo/mytodo'
      JWT_SECRET: '123456'
      EMAIL: 'nghiepradeon@gmail.com'
      PASSWORD: 'mmbfepeyqzgawrhy'
      TOKEN_EXPIRED: 300
      BUCKET_NAME: 'uploads'
      BASIC_USER: 'my_basic_user'
      BASIC_PASSWORD: 'my_basic_password'
      HOST: 'http://localhost:5000'

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    networks:
      - common

networks:
  common:


